server:
  port: 8080

--- # db
spring:
  profile: db
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password:

--- # domain1
spring:
  profiles: domain1
server:
  port: 80
  servlet:
    context-path: /domain1

--- # domain2
spring:
  profile: domain2
server:
  port: 80
  servlet:
    context-path: /domain2

--- # domain3
spring:
  profile: domain3
server:
  port: 80
  servlet:
    context-path: /domain3

--- # domain4
spring:
  profile: domain4
server:
  port: 80
  servlet:
    context-path: /domain4

--- # domain5
spring:
  profile: domain5
server:
  port: 80
  servlet:
    context-path: /domain5